#!/usr/bin/env bash
# psana_env.sh -- activate psana and set the SIT_* variables it needs.
#
#   source psana_env.sh
#
# CONFIGURATION. Do not edit this file -- it is tracked, and a machine-specific
# path in it becomes everyone's merge conflict. Instead write `psana_env.local`
# next to it (gitignored); it is sourced first if present:
#
#   # psana_env.local
#   PSANA_ENV=/home/groups/darve/hippowal/sw/envs/ana-4.0.62
#   PSANA_PSDM=/home/groups/darve/hippowal/psdm
#   PSANA_CONDA_SH=/home/groups/darve/hippowal/sw/miniforge/etc/profile.d/conda.sh
#
# PSANA_CONDA_SH is only needed where `conda` is not already on PATH, which is
# the normal case inside a batch job. See docs/PSANA_XTC.md for the one-time
# install.
#
# This script FAILS LOUDLY if activation does not take. The previous version
# printed a warning and carried on, which meant a mistyped prefix left you on
# the system python with psana missing -- discovered several steps later, as a
# confusing ImportError.

_psana_setup() {
    local here envp psdm
    here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    # shellcheck disable=SC1091
    [ -f "$here/psana_env.local" ] && source "$here/psana_env.local"

    envp="${PSANA_ENV:-}"
    psdm="${PSANA_PSDM:-}"
    if [ -z "$envp" ] || [ -z "$psdm" ]; then
        echo "psana_env.sh: set PSANA_ENV and PSANA_PSDM in $here/psana_env.local" >&2
        echo "              (see the header of this file for a template)" >&2
        return 1
    fi
    [ -d "$envp" ] || { echo "psana_env.sh: no such conda env: $envp" >&2; return 1; }

    export SIT_PSDM_DATA="$psdm"
    export SIT_ROOT="$psdm/sit_root"     # any valid dir; global calib repo (unused here)
    export SIT_DATA="$psdm/data"         # must contain ExpNameDb/experiment-db.dat
    mkdir -p "$SIT_ROOT/detector/calib/constants" "$SIT_DATA/ExpNameDb" || {
        echo "psana_env.sh: cannot write under $psdm -- pick a writable PSANA_PSDM" >&2
        return 1
    }

    # minimal experiment registry: "<expnum> <instrument> <experiment>"
    if [ ! -s "$SIT_DATA/ExpNameDb/experiment-db.dat" ]; then
        echo "1016922 xpp xppl1016922" > "$SIT_DATA/ExpNameDb/experiment-db.dat"
    fi

    # Activate. In a batch job `conda` is usually not on PATH, hence PSANA_CONDA_SH.
    if [ -n "${PSANA_CONDA_SH:-}" ] && [ -f "$PSANA_CONDA_SH" ]; then
        # shellcheck disable=SC1090
        source "$PSANA_CONDA_SH"
    elif command -v conda >/dev/null 2>&1; then
        # shellcheck disable=SC1091
        source "$(conda info --base)/etc/profile.d/conda.sh"
    else
        echo "psana_env.sh: conda not on PATH; set PSANA_CONDA_SH to its" >&2
        echo "              profile.d/conda.sh in psana_env.local" >&2
        return 1
    fi
    conda activate "$envp" || {
        echo "psana_env.sh: conda activate '$envp' failed" >&2; return 1; }

    # Prove it took, rather than trusting it.
    case "$(command -v python)" in
        "$envp"/*) ;;
        *) echo "psana_env.sh: activation did not take -- python is" \
                "$(command -v python), not in $envp" >&2; return 1 ;;
    esac
    python -c "import psana" 2>/dev/null || {
        echo "psana_env.sh: '$envp' has no psana -- see docs/PSANA_XTC.md" >&2
        return 1; }

    echo "psana env ready:"
    echo "  SIT_PSDM_DATA=$SIT_PSDM_DATA"
    echo "  SIT_ROOT=$SIT_ROOT"
    echo "  SIT_DATA=$SIT_DATA"
    echo "  python: $(command -v python)"
}

# `return` when sourced, `exit` when executed. Detected here at top level: a
# bare `return` is legal in a sourced script and an error in an executed one.
if _psana_setup; then
    :
else
    (return 0 2>/dev/null) && return 1 || exit 1
fi
